// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulbsrnosehxzsysuyzsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsYnNybm9zZWh4enN5c3V5enNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0OTM1MTAsImV4cCI6MjA2MzA2OTUxMH0.IlK3h4VkG9e96Xu3-RtRgo3gDovdgrEwYZSFkvQvGVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);